# Generated by Django 2.1.5 on 2019-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
            ],
        ),
    ]
