# Generated by Django 2.1.5 on 2019-12-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_input', models.CharField(max_length=50)),
                ('device_input', models.CharField(max_length=50)),
                ('unique_id_input', models.CharField(max_length=50)),
            ],
        ),
    ]
