# Generated by Django 2.1.5 on 2019-12-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='device_input',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='place_input',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='unique_id_input',
            new_name='unique_id',
        ),
    ]
