# Generated by Django 2.1.5 on 2019-12-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191218_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
