# Generated by Django 2.1.5 on 2019-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_place_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='icon_class',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
